# Generated by Django 3.2.6 on 2023-01-11 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('heart_rate', models.PositiveIntegerField()),
                ('blood_pressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_of_visit', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
