# Generated by Django 3.2.6 on 2023-01-11 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
